### ISSUE TITLE
simple question

### ISSUE THREAD

**Issue by maasencioh** [mljs/libsvm#1]
Hi @stropitek! I wonder why this module, if we already have https://github.com/mljs/svm ?

**Comment by stropitek** [comment]
Hey @maasencioh 
The current library is based on very simplistic version of the algorithm, more destined for students to learn the algorithm than for people to use it... libsvm uses some complex heuristics to make it faster, and it also enables several type of SVMs, including support vector regressions! It's also a pretext for learning a little bit of emscripten :smile: 
If you want to know more about the library: https://www.csie.ntu.edu.tw/~cjlin/libsvm/

**Comment by maasencioh** [comment]
well, I hope that when you finish them we can make them compite for a while! 💪 😄
